# Generated by Django 4.0.4 on 2022-05-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100, verbose_name='Nombres')),
                ('direction', models.CharField(max_length=100, verbose_name='Direccion')),
                ('email', models.EmailField(max_length=254, verbose_name='Correa')),
                ('mobile', models.CharField(max_length=20, verbose_name='Celular')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creado')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de editado')),
            ],
            options={
                'verbose_name': 'venta',
                'verbose_name_plural': 'ventas',
                'ordering': ['-id'],
            },
        ),
    ]
