# Generated by Django 4.0.4 on 2022-05-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_venta_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='email',
            field=models.EmailField(max_length=250),
        ),
        migrations.AlterField(
            model_name='venta',
            name='mobile',
            field=models.CharField(max_length=30, verbose_name='Celular'),
        ),
    ]
