# Generated by Django 4.0.4 on 2022-05-25 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_venta_email_alter_venta_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stok',
            field=models.IntegerField(default=50, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='image',
            field=models.ImageField(default='null', upload_to='producto', verbose_name='Imagen'),
        ),
    ]
