# Generated by Django 4.0.4 on 2022-05-25 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_producto_stok_alter_producto_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='unit',
            field=models.IntegerField(default=0, verbose_name='Unidad'),
        ),
    ]
